name: 'EKS Helm'
description: 'Run Helm with EKS clusters'
inputs:
  args:
    description: 'Helm arguments'
    required: true
  eksCluster:
    description: 'EKS cluster name'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.eksCluster }}
    - ${{ inputs.args }}
